version: '3'
services:
  jekyll:
    image: "jekyll/jekyll:3.5"
    ports:
      - 4000:4000
      - 35729:35729
      - 3000:3000
      -   80:4000
    volumes: 
      - ./:/srv/jekyll
    command: jekyll serve