version: '3'
services:
  node:
    image: "node:10.12.0-alpine"
    ports:
      - "8000:8000"
    volumes: 
      - ./:/home/app
    working_dir: /home/app
    command: >
      sh -c "
      npm install;
      npm run develop;"

